# Generated by Django 5.0.7 on 2024-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='company_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
